stages:
- build
- staging

build:
  stage: build
  tags:
    - front.ylab.io
  only:
  - develop
  script:
  - npm install
  cache:
    paths:
    - node_modules
  artifacts:
    paths:
    - ./
    expire_in: 1 hour

staging:
  stage: staging
  tags:
    - front.ylab.io
  script:
  - rsync -rlv --exclude=.git ./ /home/user/example/server
  - cd /home/user/example/server
  - npm run init-example
  #- /home/user/pm2.sh delete process.json
  - /home/user/pm2.sh restart process.json
  only:
  - develop
