###
# SignIn

POST {{baseUrl}}/users/sign?fields=*
Content-Type: application/json

{
  "login": "test",
  "password": "123456"
}

###
# GET current by XToken

GET {{baseUrl}}/users/self?fields=*
Content-Type: application/json
X-Token: {{tokenAdmin}}

###
# GET list

GET {{baseUrl}}users?fields=_id,email,profile(*)
X-Token:{{tokenAdmin}}
Content-Type: application/json


###
# GET by id

GET {{baseUrl}}users/6082e47fe646400a3c62d3b6?fields=_id,email,profile(*)
X-Token:{{tokenAdmin}}
Content-Type: application/json

###
# Change password

PUT {{baseUrl}}users/6082e47fe646400a3c62d3b6/password
X-Token:{{tokenAdmin}}
Content-Type: application/json

{
  "oldPassword":"123456",
  "newPassword":"1234567"
}

###
# Create or registre new user

POST {{baseUrl}}/users?fields=order
Content-Type: application/json

{
  "email": "boolive@yandex.ru",
  "profile": {
    "name": "Владимир",
    "surname": "Шестаков"
  }
}



###
